# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{forgetful}
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jonathan Palardy"]
  s.date = %q{2011-04-19}
  s.default_executable = %q{forgetful}
  s.description = %q{A minimal command-line implementation of the SuperMemo 2 algorithm.}
  s.email = %q{jonathan.palardy@gmail.com}
  s.executables = ["forgetful"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/forgetful",
    "examples/katakana_romaji.csv",
    "examples/romaji_katakana.csv",
    "lib/forgetful.rb",
    "lib/forgetful/cli.rb",
    "lib/forgetful/csv_ext/reminder.rb",
    "lib/forgetful/reminder.rb",
    "lib/forgetful/supermemo.rb",
    "spec/reminder_csv_spec.rb",
    "spec/reminder_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/supermemo_spec.rb"
  ]
  s.homepage = %q{http://github.com/jpalardy/forgetful}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A minimal command-line implementation of the SuperMemo 2 algorithm.}
  s.test_files = [
    "spec/reminder_csv_spec.rb",
    "spec/reminder_spec.rb",
    "spec/spec_helper.rb",
    "spec/supermemo_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, ["= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, ["= 1.2.9"])
  end
end

